# Generated by Django 4.2.6 on 2023-10-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name', max_length=100, verbose_name='Seller name')),
                ('surname', models.CharField(help_text='Enter surname', max_length=100, verbose_name='Seller surname')),
                ('email', models.EmailField(help_text='Enter email', max_length=254, unique=True, verbose_name='Seller email')),
                ('phone', models.CharField(help_text='Enter phone', max_length=12, unique=True, verbose_name='Seller phone')),
                ('date_of_employment', models.DateField(help_text='Enter date of employment', verbose_name='Seller date of employment')),
                ('position', models.CharField(choices=[('Seller', 'Seller'), ('Senior Manager', 'Senior Manager'), ('Head of department', 'Head of department')], help_text='Enter position', max_length=100, verbose_name='Seller position')),
            ],
        ),
    ]
