# Generated by Django 4.2.6 on 2023-10-08 08:15

import Company__sales.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0002_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateField(help_text='Enter date of sale', validators=[Company__sales.models.checkDate], verbose_name='Date of sale')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Enter price', max_digits=10, verbose_name='Price')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company__sales.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company__sales.item')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company__sales.seller')),
            ],
        ),
    ]
