# Generated by Django 4.2.6 on 2023-10-10 14:53

import Company__sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0003_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Enter phone', max_length=12, unique=True, validators=[Company__sales.models.phone_validator], verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(help_text='Enter phone', max_length=12, unique=True, validators=[Company__sales.models.phone_validator], verbose_name='Seller phone'),
        ),
    ]
