# Generated by Django 4.2.6 on 2023-10-10 16:53

import Company__sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0005_alter_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Enter email22', max_length=254, unique=True, verbose_name='Customer email44'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Enter name22', max_length=100, verbose_name='Customer name44'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Enter phone22', max_length=12, unique=True, validators=[Company__sales.models.phone_validator], verbose_name='Customer phone44'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(help_text='Enter surname22', max_length=100, verbose_name='Customer surname44'),
        ),
    ]
