# Generated by Django 4.2.6 on 2023-10-10 16:54

import Company__sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0006_alter_customer_email_alter_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(help_text='Enter email', max_length=254, unique=True, verbose_name='Customer email'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(help_text='Enter name', max_length=100, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(help_text='Enter phone', max_length=12, unique=True, validators=[Company__sales.models.phone_validator], verbose_name='Customer phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(help_text='Enter surname', max_length=100, verbose_name='Customer surname'),
        ),
    ]
