# Generated by Django 4.2.6 on 2023-10-11 09:24

import Company__sales.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0008_alter_seller_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='date_of_employment',
            field=models.DateField(help_text='Enter date of employment', validators=[Company__sales.models.checkDate], verbose_name='Seller date of employment'),
        ),
    ]
