# Generated by Django 4.2.6 on 2023-10-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0009_alter_seller_date_of_employment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter price', max_digits=10, verbose_name='Price'),
        ),
    ]
