# Generated by Django 4.2.6 on 2023-10-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company__sales', '0010_remove_sale_price_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Enter price, $', max_digits=10, verbose_name='Price, $'),
        ),
    ]
